services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    volumes:
      - ./mongo/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT:-27017}:27017"

  node-app:
    build: ./node-app
    container_name: node-app
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://appuser:apppass@mongo:27017/appdb?authSource=appdb
    ports:
      - "${NODE_APP_PORT}:3000"

  python-app:
    build: ./python-app
    container_name: python-app
    environment:
      - MONGO_URL=${MONGO_URL}
    depends_on:
      - mongo
    ports:
      - "${PYTHON_APP_PORT}:5000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - node-app
      - python-app

